---
title: "Analysis Resources"
bibliography: library.bib
biblio-style: apalike
---

```{r, child="_setup.Rmd"}
```
#### \   

# Setting Disciplinary/Topic Learning Outcomes 

If your local program does not have learning outcome goals developed already, the 2011 Vision and Change in Undergraduate Biology Education report (V&C) is a good reference resource. The original report was the culmination of a 10-year effort to develop a consensus among stakeholders at the local and national levels of what disciplinary knowledge and skills undergraduates should have after their first year of biology courses. Subsequent reports have established assessment criteria for the V&C goals, and several professional groups exist whose aim is to implement V&C's goals nationally. Several sub-groups within biology are using the V&C model to establish foundational learning goals for students starting out in their fields of study. 

Slide46.jpeg

_An example of how V&C's very broad goals were reframed as specific concepts that connect to one another, and provide anchor points for assessing student learning._

#### \  

## To Learn More
### Local Resources

* V&C Expanded 2011 Report. No longer available online. 
[Download only](downloads/FinalReportVisionChange2011.pdf).

* Bibliography of articles articles published in CBE-Life Sciences Education relating to V&C from 2009 to Jan. 2024. 
[Download](downloads/VCArticleList.md).

* Examples of knowledge goals tables from Brownell 2014. 
[Download](downloads/GeneralKnowledge.pptx).

#### \  

### External Resources

* V&C 2011 Summary Report. [Links to an external site](https://www.aaas.org/sites/default/files/content_files/VC_report.pdf).

* Brownell, 2014. First framework of specific performance goals for V&C. [Links to an external site](https://pubmed.ncbi.nlm.nih.gov/26086653/).

* Clemmons, 2020. Development and validation of BioSkills Guide, a tool for interpreting V&C competencies. [Links to an external site](https://pubmed.ncbi.nlm.nih.gov/33001766/). 

* PULSE Community. A prominent stakeholders group working on national implementation. [Links to an external site](https://pulse-community.org/). 

* A 2023 article by [Clark and Hsu](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC10074271/)\cite{Clark2023} is a good overview of the process.

* Here are two examples of program-level general learning outcomes. Individual courses within the programs would be designed to meet a subset of these outcomes.
    + [Indiana University](https://biology.indiana.edu/undergraduate/biology/learning-goals.html)
    + [Bates College](https://www.bates.edu/biology/biology-at-bates/learning-goals/)

#### \  

## Sources of Questions About Motivation and Interest

* [Rowland et al.'s 2019 literature review](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6755315/)\cite{Rowland2019}  of methods for defining and measuring student interest in biology.
* [Biology Self-Efficacy Scale](https://doi.org/10.1002/(SICI)1098-237X(199907)83:4%3C397::AID-SCE1%3E3.0.CO;2-%23)
* [Intrinsic Motivation Inventory, or IMI](https://selfdeterminationtheory.org/intrinsic-motivation-inventory/) 
* [Motivated Strategies for Learning Questionnaire, or MSLQ](https://psycnet.apa.org/doi/10.1037/0022-0663.82.1.33) 
* [The standard survey I use to gather data on student motivation and goals](downloads/Semester_startup_survey.md).

#### \  

# Setting Topic-Independent Learning Outcomes

The __Teaching Goals Inventory__, developed by Angelo and Cross (1993) is a good tool for identifying learning outcomes that are independent of course content and concepts knowledge goals. TGI was designed to: 

* help faculty choose informal classroom assessment methods; 
* help individual faculty members become aware of course goals; and 
* provide a starting point for discussion between colleagues. 

TGI also has proven extremely useful as a catalyst for new course development, and for analyzing connections between courses in a curricular sequence. The developers have given permission for the Inventory to be used freely, and it is [available online.](https://tgi.its.uiowa.edu/) 

#### \ 

<hr>
