---
title: "Using Markdown"
bibliography: library.bib
biblio-style: apalike
---

```{r, child="_setup.Rmd"}
```
#### \   

Sometimes case documents need to be written so they can be converted for multiple outputs: .docx files for printed handouts, .pdf for download-ready files, or .html for the campus LMS or the web generally. Managing multiple versions of documents can be difficult if you do not have a systematic strategy. My approach has been to draft most materials in **Markdown** then convert the files to other formats. The added advantage is that Markdown is the standard text formatting method for many other programs like R Studio, etc.  

Markdown is a simple-to-use formatting language for authoring small, reusable plain text documents. The philosophy behind Markdown is "write text once, then output it in many formats." Markdown can quickly convert from one format into more than 30 different formats for web pages, printed handouts, and slide presentations. Groups of Markdown files can be combined to create interactive online books and web site. For example, this entire web site was written in R Studio's variant, R Markdown. Several downloadable documents are written in plain Markdown (.md extension) or R Markdown (.Rmd extension). 

* The [page on Markdown conversion](markdown_conversion.html) describes how to convert files to other formats.
* To learn more about using Markdown and the R Markdown variant see [http://rmarkdown.rstudio.com](http://rmarkdown.rstudio.com).

#### \   

<hr>